#include <unistd.h>

void	putstr (char *str)
{
	int	i;
	i = 0;
	while(str[i])
		write(1, &str[i++], 1);
}

int	main ()
{
	putstr("Growth Marketer, Mid-Level (L2)\nSELANGOR /MARKETING – GROWTH MARKETING /FULL-TIME\nSUBMIT YOUR APPLICATION\nGROWTH MARKETING - PERSONAL STATEMENT - ALL LEVELS\n\nWhy are you interested in joining CoinGecko? Where do you see yourself contributing best in the team?\nI am enthusiastic in promoting the things I do, marketing and PR is where I think I could benefit the team. Having a solid 5 years marketing and trade promotion experience in the timber industry before joining the manufacturing sector. Did statistical analysis, report writing, market survey in MENA and across Malaysia. I believe I will ignite the passion in any individual about the long term sustainable usage of natural solid timber.\nDid some stock trading before, so I am familiar with technical analysis (TA); the historical charts, the indicators, moving averages et cetera. Might be able to give some input on day trading.\n\n");
	putstr("In CoinGecko, we believe in continuous learning. Tell us about a recent skill you have developed either on or off work, and how you approached the process.\nJoined the 42KL to learn coding as it is the skill of the 21st century, I am keenly interested in the development of digital cryptography; as the use in database security, monetary and information transactions continue to be mainstream. New to peer to peer learning, I mingle with the fellow students, brainstormed and learned coding from each other. Most of the other time were spent scouring the net for solutions and for understanding about the basic language of C. That is a start, now I've learned to code; and more importantly learned to learn to code. Hence, Solidity, web3.js here I come!\n\n");
	putstr("Assume that CoinGecko has just launched our Portfolio feature. Write 3 paragraphs introducing this feature to the public.\nWhat is CoinGecko? It is a free resource or information source for all your cyptocurrency needs. From a pure beginner to being a pro in the cryptocurrency world, CoinGecko will satisfy the information you seek. Browse through the resource tab and publications tab in the website for all the info you need. Start your journey with the free and powerful crypto portfolio tracker NOW! https://www.coingecko.com/en/portfolio\nFor the seasoned investor trying to switch over or to increase your portfolio to include crytocurrency, look no further, coingecko gets you covered. You get to choose which of the 13,222 cyptocurrency to buy, based on largest market cap, largest daily trade volume or if you like to buy the latest coin in the market. You can buy via CoinGecko! And just like when you are monitoring stocks, you get to monitor the historical charts of your favourite coins, complete with candlestick patterns, and most of if not all the indicators you use, e.g., MACD, Stochastic RSI, Bollinger Bands, and much much more! Hence, you will make a vey very informed decision when buying cryptocurrencies via CoinGecko!\nThere's more! You can buy and sell your cryptocurrencies through the CoinGecko platform. Moreover you can monitor your favourite exchange you use or monitor the DeFi coins you've been eyeing for. No need to scroll further for that sign up page. Here you go! https://www.coingecko.com/en/portfolio\nYou're welcome!\n\n");
	putstr("Reflecting on your academic and/or professional career, were there times where you felt you were not as successful as you would have liked? What were they and why did they occur? What were the lessons?\nIn Dubai whilst managing a woodworking factory, trusting your subordinates and your contractors to deliver may be a tall order; especially when their contract seems too good to be true and your subordinates are yes men. Lessons learnt, always quadruple check to ensure the work is on schedule, goods are delivered as per contract, work done by subordinates are of satisfactory quality of at the very least MVP. There are situations where micro-managing is a necessity.\n\n");
	putstr("ADDITIONAL INFORMATION\nMaking the paragraph long contents I submitted on this page into a C programme with only using the write function and not using the standard IO library or <stdio.h>. ");
}